name: Publish Site
  on:
    push:
      branches:
        - main  # default branch

    - name: Deploy
    uses: peaceiris/actions-gh-pages@v3
    with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: main  # deploying branch
